name: Generate and Upload Video

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

- name: Install moviepy manually
  run: pip install moviepy

    - name: Generate Video
      run: |
        source venv/bin/activate
        python generate_video.py

    - name: Upload Video to YouTube
      env:
        CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
      run: |
        source venv/bin/activate
        python upload_video.py
