name: Auto Video Upload

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Change to '3.10' or '3.11' if needed

      - name: Update package lists
        run: sudo apt-get update --fix-missing

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg 

      - name: Verify FFmpeg installation
        run: ffmpeg -version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Debug installed packages
        run: pip list

      - name: Run video generation script
        run: python generate_video.py
